# Assignment


**WRITE 20 INBUILTS METHODS OF NUMPY AND PANDAS



# The Sorting Numpy Array method
An array is basically a data structure which can hold more than one value at a time.

In [6]:
#Example in code:
import numpy as np
a = ([6,8,9,5,7,4,2])
a = np.array([ 6, 8, 9, 5, 7, 4, 2])
print(np.sort(a))

[2 4 5 6 7 8 9]


In [10]:
import numpy as np
nums = np.array([[2,4,6], [8,10,12], [14,16,18]])
print(nums)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# the Arange method
#This method takes the start index of the array, the end index, and the step size (which is optional).


In [12]:
#Example in code:
import numpy as np
numbers = np.arange(2, 7)
print(numbers)

[2 3 4 5 6]


# The linspace method
The linspace()method returns evenly spaced values within a given interval. Like arange() function, linspace() function can also be used to create a NumPy array but with more discipline. 

In [13]:
#Examples in code:
lin = np.linspace(1, 10, 10)
print(lin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [14]:
my_lin = np.linspace(1, 10, 20)
print(my_lin)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


# The Eye method
The eye method is used to create an identity matrix, which can be very useful to perform a variety of operations in linear algebra. An identity matrix is a matrix with zeros across rows and columns except the diagonal. The diagonal values are all ones.

In [16]:
idn = np.eye(4)
print(idn)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# The Random() method 
it returns a random floating number between 0 and 1.

In [18]:
rams = np.random.rand(2, 3)
type(rams)
print(rams)

[[0.42731897 0.15305389 0.54132065]
 [0.70448016 0.75854867 0.00256703]]


# The Randit method
it is used to to create an array of random integers.
The randint method takes the lower bound, upper bound, and the number of integers to return.

In [19]:
random = np.random.randint(50, 100, 5)
print(random)

[61 61 77 96 54]


# The Reshaping method
it is used to convert one dimensional array into two dimensional array

In [21]:
my_numbers = np.arange(1,17)
print(my_numbers)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [23]:
my_numbers2 = my_numbers.reshape(4,4)
print(my_numbers2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# The Max Methods
it is used to find the largest number in an array

In [24]:
my_lists = np.random.randint(1,100,5)
print(my_lists)

[90 80 96 86 30]


In [25]:
Xmax = my_lists.max()
print(Xmax)

96


# The Min methods
it is used to find the smallest numbers in an array

In [27]:
Xmin = my_lists.min()
print(Xmin)

30


# The argmax methods
it is used to calculate the 

In [28]:
argmax = my_lists.max()
print(argmax)

96


# The argmin methods
It is used to calculate the 

In [31]:
my_list = np.random.randint(1,100,5)
argmin = my_list.min()
print(argmin)

15


# Indexing with 2-D arrays method
NumPy arrays with two dimensions also follow the zero-based index, that is, in order to access the elements in the first row, you have to specify 0 as the row index. Similarly to access elements in the first column, you need to specify 0 for the column index as well.

In [37]:
numbers2d = np.array(([1,2,3], [4,5,6], [7,8,9]))
print(numbers2d)
print(numbers2d[0,0])
print(numbers2d[2,2])
print(numbers2d[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
[1 2 3]


# Transposing the Numpy Array
it is used to transpose numpy array

In [38]:
a = np.arange(12).reshape((6,2))
a.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

# Concatenate multiple Numpy arrays to form one Numpy Array
The np.concatenate is used to join a sequence of arrays and obtain a new numpy array

In [39]:
#concatenate row-wise
b = np.array([[1,2],[3,4]])
c = np.array([[5,6]])
np.concatenate((b,c),axis=0) 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
#concatenate column-wise
b = np.array([[1,2],[3,4]])
c = np.array([[5,6]])
np.concatenate((b,c.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

# Squeeze Numpy Array
it removes axes of length one from Numpy Array 

In [44]:
x = np.array(([0], [1], [2]))
x.shape
np.squeeze(x).shape

(3,)

# Trigonometric functions

In [47]:
a = np.array([1,2,3])
print('trigonometric sine:', np.sin(a))
print('trigonometric cosine:', np.cos(a))
print('trigonometric tangent:', np.tan(a))

trigonometric sine: [0.84147098 0.90929743 0.14112001]
trigonometric cosine: [ 0.54030231 -0.41614684 -0.9899925 ]
trigonometric tangent: [ 1.55740772 -2.18503986 -0.14254654]


# Exponents and Logarithms

In [49]:
b = np.arange(1,6)
print(b)

[1 2 3 4 5]


In [50]:
np.exp(a).round(2)


array([ 2.72,  7.39, 20.09])

In [51]:
np.log(a).round(2)

array([0.  , 0.69, 1.1 ])

# The Squareroot Methods

In [54]:
numbers4 = np.sqrt(rams)
print(numbers4)

[[0.65369639 0.39122103 0.73574496]
 [0.83933316 0.87094699 0.05066591]]


# THE PANDAS METHODS

# Data head and tail()
it is used to see dataframe df.head().Head returns the first rows, if no input is given it will always show above 5 rows. In contrast to see below rows, we can use df.tail().

In [56]:

import pandas as pd
data= pd.read_csv('https://raw.githubusercontent.com/jbolla368/Pandas-using-in-EDA/master/housing_dataset.csv')

In [57]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   
4    -122.25     37.85                  52         1627           280.0   

   population  households  median_income ocean_proximity  median_house_value  
0         322         126         8.3252        NEAR BAY              452600  
1        2401        1138         8.3014        NEAR BAY              358500  
2         496         177         7.2574        NEAR BAY              352100  
3         558         219         5.6431        NEAR BAY              341300  
4         565         259         3.8462        NEAR BAY              342200

In [58]:
data.tail()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20635    -121.09     39.48                  25         1665           374.0   
20636    -121.21     39.49                  18          697           150.0   
20637    -121.22     39.43                  17         2254           485.0   
20638    -121.32     39.43                  18         1860           409.0   
20639    -121.24     39.37                  16         2785           616.0   

       population  households  median_income ocean_proximity  \
20635         845         330         1.5603          INLAND   
20636         356         114         2.5568          INLAND   
20637        1007         433         1.7000          INLAND   
20638         741         349         1.8672          INLAND   
20639        1387         530         2.3886          INLAND   

       median_house_value  
20635               78100  
20636               77100  
20637               92300  
20638               84700  
20639               89400

# Shape, Size and Info
df.shape() gives total number of rows and columns, 
df.size()returns the number of rows times number of columns in the data frame.
df.info()we get different information such as rows from RangeIndex, Data columns 
and then data type of each column. It also includes the information of non-null counts.

In [76]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  int64  
 3   total_rooms         20640 non-null  int64  
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  int64  
 6   households          20640 non-null  int64  
 7   median_income       20640 non-null  float64
 8   ocean_proximity     20640 non-null  object 
 9   median_house_value  20640 non-null  int64  
dtypes: float64(4), int64(5), object(1)
memory usage: 1.6+ MB


In [71]:
data.shape

(20640, 10)

In [72]:
data.dtypes

longitude             float64
latitude              float64
housing_median_age      int64
total_rooms             int64
total_bedrooms        float64
population              int64
households              int64
median_income         float64
ocean_proximity        object
median_house_value      int64
dtype: object

In [73]:
data.size

206400

# Describe

In [75]:
data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [77]:
data.describe(include = 'all').T

count unique        top  freq           mean  \
longitude           20640.0    NaN        NaN   NaN    -119.569704   
latitude            20640.0    NaN        NaN   NaN      35.631861   
housing_median_age  20640.0    NaN        NaN   NaN      28.639486   
total_rooms         20640.0    NaN        NaN   NaN    2635.763081   
total_bedrooms      20433.0    NaN        NaN   NaN     537.870553   
population          20640.0    NaN        NaN   NaN    1425.476744   
households          20640.0    NaN        NaN   NaN      499.53968   
median_income       20640.0    NaN        NaN   NaN       3.870671   
ocean_proximity       20640      5  <1H OCEAN  9136            NaN   
median_house_value  20640.0    NaN        NaN   NaN  206855.816909   

                              std      min       25%       50%       75%  \
longitude                2.003532  -124.35    -121.8   -118.49   -118.01   
latitude                 2.135952    32.54     33.93     34.26     37.71   
housing_median_age      12.585558      1.0      18.0      29.0      37.0   
total_rooms           2181.615252      2.0   1447.75    2127.0    3148.0   
total_bedrooms          421.38507      1.0     296.0     435.0     647.0   
population            1132.462122      3.0     787.0    1166.0    1725.0   
households             382.329753      1.0     280.0     409.0     605.0   
median_income            1.899822   0.4999    2.5634    3.5348   4.74325   
ocean_proximity               NaN      NaN       NaN       NaN       NaN   
median_house_value  115395.615874  14999.0  119600.0  179700.0  264725.0   

                         max  
longitude            -114.31  
latitude               41.95  
housing_median_age      52.0  
total_rooms          39320.0  
total_bedrooms        6445.0  
population           35682.0  
households            6082.0  
median_income        15.0001  
ocean_proximity          NaN  
median_house_value  500001.0

# Missing Values in the dataset

In [78]:
data.isnull()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False   
1          False     False               False        False           False   
2          False     False               False        False           False   
3          False     False               False        False           False   
4          False     False               False        False           False   
...          ...       ...                 ...          ...             ...   
20635      False     False               False        False           False   
20636      False     False               False        False           False   
20637      False     False               False        False           False   
20638      False     False               False        False           False   
20639      False     False               False        False           False   

       population  households  median_income  ocean_proximity  \
0           False       False          False            False   
1           False       False          False            False   
2           False       False          False            False   
3           False       False          False            False   
4           False       False          False            False   
...           ...         ...            ...              ...   
20635       False       False          False            False   
20636       False       False          False            False   
20637       False       False          False            False   
20638       False       False          False            False   
20639       False       False          False            False   

       median_house_value  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
...                   ...  
20635               False  
20636               False  
20637               False  
20638               False  
20639               False  

[20640 rows x 10 columns]

In [79]:
data.isna().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
ocean_proximity       False
median_house_value    False
dtype: bool

In [80]:
data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
median_house_value      0
dtype: int64

# loc and iloc
it is used to select by labels

In [81]:
data.loc[:5,['median_income', 'median_house_value']]

median_income  median_house_value
0         8.3252              452600
1         8.3014              358500
2         7.2574              352100
3         5.6431              341300
4         3.8462              342200
5         4.0368              269700

In [82]:
data.iloc[:4,:6]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   

   population  
0         322  
1        2401  
2         496  
3         558

# Slicing


In [83]:
data[0:4]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   

   population  households  median_income ocean_proximity  median_house_value  
0         322         126         8.3252        NEAR BAY              452600  
1        2401        1138         8.3014        NEAR BAY              358500  
2         496         177         7.2574        NEAR BAY              352100  
3         558         219         5.6431        NEAR BAY              341300

# Nunique
it counts the number of unique entries over the column or rows, very useful in categorical features.

In [84]:
data.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
ocean_proximity           5
median_house_value     3842
dtype: int64

# sample

In [85]:
data.sample(n=8)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
13060    -121.28     38.60                  17         1671           378.0   
7704     -118.14     33.96                  34         2744           541.0   
11038    -117.80     33.83                  17         2971           350.0   
16564    -121.52     37.75                  18         1544           272.0   
16757    -122.48     37.70                  33         4492             NaN   
18792    -122.57     40.61                  27         1540           315.0   
7277     -118.25     33.99                  41         1486           509.0   
20534    -121.74     38.56                  18         3960          1151.0   

       population  households  median_income ocean_proximity  \
13060         848         351         3.1194          INLAND   
7704         1333         503         4.0536       <1H OCEAN   
11038        1180         346        11.1228       <1H OCEAN   
16564         825         286         4.3229          INLAND   
16757        3477        1537         3.0546      NEAR OCEAN   
18792         883         321         2.8036          INLAND   
7277         2312         541         1.3963       <1H OCEAN   
20534        2248        1144         1.7257          INLAND   

       median_house_value  
13060              112500  
7704               277200  
11038              500001  
16564              327300  
16757              297900  
18792               93400  
7277                92900  
20534              179100

# Groupby Function

In [88]:
data[['housing_median_age', 'median_house_value','total_rooms']].groupby('median_house_value').agg(['mean','count'])

housing_median_age        total_rooms      
                                 mean count         mean count
median_house_value                                            
14999                       30.750000     4   443.750000     4
17500                       39.000000     1   493.000000     1
22500                       36.250000     4  2805.750000     4
25000                       21.000000     1    44.000000     1
26600                       34.000000     1  1440.000000     1
...                               ...   ...          ...   ...
498800                      29.000000     1  1945.000000     1
499000                      18.000000     1  4845.000000     1
499100                      28.000000     1  2024.000000     1
500000                      38.000000    27  2202.037037    27
500001                      33.802073   965  2961.968912   965

[3842 rows x 4 columns]

# Index

In [89]:
data.index

RangeIndex(start=0, stop=20640, step=1)

# Columns

In [90]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity', 'median_house_value'],
      dtype='object')

# Sorting

In [91]:
data.sort_index(axis=1, ascending=True)

households  housing_median_age  latitude  longitude  \
0             126                  41     37.88    -122.23   
1            1138                  21     37.86    -122.22   
2             177                  52     37.85    -122.24   
3             219                  52     37.85    -122.25   
4             259                  52     37.85    -122.25   
...           ...                 ...       ...        ...   
20635         330                  25     39.48    -121.09   
20636         114                  18     39.49    -121.21   
20637         433                  17     39.43    -121.22   
20638         349                  18     39.43    -121.32   
20639         530                  16     39.37    -121.24   

       median_house_value  median_income ocean_proximity  population  \
0                  452600         8.3252        NEAR BAY         322   
1                  358500         8.3014        NEAR BAY        2401   
2                  352100         7.2574        NEAR BAY         496   
3                  341300         5.6431        NEAR BAY         558   
4                  342200         3.8462        NEAR BAY         565   
...                   ...            ...             ...         ...   
20635               78100         1.5603          INLAND         845   
20636               77100         2.5568          INLAND         356   
20637               92300         1.7000          INLAND        1007   
20638               84700         1.8672          INLAND         741   
20639               89400         2.3886          INLAND        1387   

       total_bedrooms  total_rooms  
0               129.0          880  
1              1106.0         7099  
2               190.0         1467  
3               235.0         1274  
4               280.0         1627  
...               ...          ...  
20635           374.0         1665  
20636           150.0          697  
20637           485.0         2254  
20638           409.0         1860  
20639           616.0         2785  

[20640 rows x 10 columns]

# query

In [92]:
data.query('5000<total_rooms<5500')[:5]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
95     -122.26     37.80                  36         5329          2477.0   
116    -122.25     37.83                  28         5022          1750.0   
125    -122.22     37.85                  28         5287          1048.0   
133    -122.21     37.83                  34         5065           788.0   
391    -122.30     37.90                  15         5083          1212.0   

     population  households  median_income ocean_proximity  median_house_value  
95         3469        2323         2.0096        NEAR BAY              130000  
116        2558        1661         2.4234        NEAR BAY              218500  
125        2031         956         5.4570        NEAR BAY              337300  
133        1627         766         6.8976        NEAR BAY              333300  
391        2420        1146         4.5824        NEAR BAY              256100